export namespace ActivitySettings {
    export const EVENTS_ATTENDED_THRESHOLD_FOR_INITIATE_GRADUATE = 4;
    export const EVENTS_ATTENDED_THRESHOLD_FOR_INITIATE_BUMP = 2;
    export const EVENTS_ATTENDED_THRESHOLD_FOR_SENIOR_OR_HIGHER = 0;
    export const EVENTS_ATTENDED_THRESHOLD = 2;
    export const DISCORD_HOURS_ACTIVITY_THRESHOLD = 10;
    export const DISCORD_HOURS_ACTIVITY_THRESHOLD_FOR_SENIOR_OR_HIGHER = 8;
    export const MAX_CONSECUTIVE_INACTIVE_MONTHS = 2;
    export const DISCORD_ACTIVITY_THRESHOLD_DAYS = 7;

    export const GGWP_ACTIVITY_REQUIREMENTS_STREAK_REQUIRED = 6;
}
