export namespace ActivitySettings {
    export const REP_ACTIVITY_THRESHOLD = 100;
    export const DISCORD_HOURS_ACTIVITY_THRESHOLD = 20;
    export const DISCORD_DAYS_THRESHOLD = 15;
    export const DISCORD_DAYS_THRESHOLD_OFFICER = 10;
    export const MAX_CONSECUTIVE_INACTIVE_MONTHS = 2;
    export const MAX_CONSECUTIVE_INITIATE_INACTIVE_MONTHS = 2;
    export const MIN_REP_EARNED_FOR_INITIATE_BUMP = 50;
    export const DISCORD_ACTIVITY_THRESHOLD_DAYS = 7;

    export const GGWP_ACTIVITY_REQUIREMENTS_STREAK_REQUIRED = 6;
    export const GGWP_MINIMUM_REP_REQUIRED = 25;
}
