import { HOUR_SECONDS } from './Date';
import { EventTypes } from '~/constants/Events';

export const EmtSettings = {
    /* post time */
    EARLY_POST_TIME_IN_DAYS: 7,
    MIN_POST_TIME_HOURS: 24,
    MAX_POST_TIME_MONTHS: 3,

    /* hosting restrictions */
    MIN_DISCORD_ATTENDEES: 2,
    HOSTING_COOLDOWN_MINUTES: 30,
    MAX_EVENT_LENGTH_DISCORD_COACHING_HOURS: 4,
    MAX_EVENT_LENGTH_DISCORD_HOURS: 2,
    MAX_EVENT_LENGTH_TWITCH_HOURS: 4,
    MAX_EVENT_LENGTH_REAL_LIFE_HOURS: 4,
    EVENT_TYPES_NO_MIN_POST_TYPE: [EventTypes.COACH, EventTypes.TRAINING],

    /* attendance awards */
    TOKEN_TIME_SECONDS: HOUR_SECONDS,
    REP_RATE_ATTENDANCE_DEFAULT: 10,
    REP_RATE_ATTENDANCE_COMMUNITY: 15,
    REP_RATE_ATTENDANCE_TWITCH: 3,
    REP_RATE_ATTENDANCE_TEAM_COACHING: -25,
    REP_RATE_ATTENDANCE_SOLO_COACHING: -35,

    /* hosting awards */
    REP_RATE_HOSTING: 5,
    MAX_HOSTING_REP_ATTENDEE_BONUS: 15,
    HOSTING_REP_EARLY_POST_BONUS: 5
};
