name: Publish
permissions: write-all

on:
  push:
    branches:
      - "master"
      - "develop"
  workflow_dispatch:
    
jobs:
  push-api-types:
    name: Push @dmgincs/api-types
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DMGINC_APP_ID }}
          private-key: ${{ secrets.DMGINC_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - run: |
          git -C ./libs/api-types config --global user.name "damageinc-bot[bot]"
          git -C ./libs/api-types config --global user.email "147310067+damageinc-bot[bot]@users.noreply.github.com"
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn
        
      - name: Bump version (prerelease)
        if: github.ref == 'refs/heads/develop'
        run: npm version prerelease

      - name: Bump version (release)
        if: github.ref == 'refs/heads/master'
        run: npm version minor

      - name: Build package
        run: yarn build

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        
      - run: git push